### ISSUE TITLE
Hello, may I ask if this code is based on the DEMO BGT60TR13C on Infineon's official website?

### ISSUE THREAD

**Issue by coffeemiaom** [fringe-innovation/ifx_demo#1]
Hello, I read your code in detail and gained a lot, but I have a question, is the development hardware DEMO BGT60TR13C on Infineon's official website, or KIT_CSK_BGT60TR13C? Looking forward to your answer, thank you

**Comment by dishierweidu** [comment]
The hardware is **DEMOBGT60TR13CTOBO1**
